version: '3'
services:
  groupware-postgres:
    image: postgis/postgis
    container_name: groupware-postgres
    logging: &logging
      options:
        max-size: '100m'
        max-file: '3'
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-groupware_dev}
      - POSTGRES_USER=${POSTGRES_USER:-groupware}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-thwlsWkd123}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD:-thwlsWkd123}
    ports:
      - '5432:5432'

  node-api:
    build:
      context: .
      dockerfile: ./services/node-api/Dockerfile
    logging:
      <<: *logging
    restart: always
    env_file:
      - .env
    volumes:
      - './logs/node-api:/app/logs'
      - './seeders/sql:/app/seeders/sql'
      - './uploads:/app/uploads'
    container_name: node-api
    # ports:
    #   - '8000:8000'
    networks:
      - groupware-net

  groupware-vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - '8200:8200'
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - vault-data:/vault/file
    healthcheck:
      retries: 5
    command: vault server -config=/vault/config/vault.json

  groupware-redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD:-kRx15FSl6lDek9g4wr3KNG7VlxoXDAOzPJ6y7eBys4MYTlMFMdKrC2joe08jB}
    volumes:
      - 'redis-data:/data'
      - './redis/redis.conf:/usr/local/etc/redis/redis.conf'
    ports:
      - '6379:6379' # redis-server
      - '8001:8001' # redis-insight
    command: "redis-server /usr/local/etc/redis/redis.conf"
    
  groupware-nginx:
    image: nginx:latest
    container_name: groupware-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/nginx/certs
    ports:
      - '8000:8000'
      - '8002:8002'
      - '5002:5002'
    depends_on:
      - node-api
    networks:
      - groupware-net
          
volumes:
    pg-data:
    redis-data:
    vault-data:
    certs:

networks:
  groupware-net: